CREATE DATABASE DEVELOPERBDTESTER
GO
USE DEVELOPERBDTESTER
GO
CREATE TABLE GAMES
(
	CODIGO			INTEGER IDENTITY(1,1)			,
	CODIGO_BARRAS		VARCHAR(100)		NULL		,
	MARCA			VARCHAR(255)		NOT NULL	,
	PLATAFORMA		VARCHAR(255)		NOT NULL	,
	IDIOMAS			VARCHAR(255)		NOT NULL	,
	FAIXA_ETARIA		VARCHAR(10)		NOT NULL	,
	CONTEUDO_EMBALAGEM	VARCHAR(255)		NOT NULL	,
	REFERENCIA_MODELO	VARCHAR(255)		NOT NULL	,
	FORNECEDOR		VARCHAR(255)		NOT NULL	,
	PRIMARY KEY(CODIGO)
)